version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/manga_translator
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/storage
      - TEMP_DIR=/app/temp
    volumes:
      - ./data/storage:/app/storage
      - ./data/temp:/app/temp

  worker:
    build:
      context: ./backend
      dockerfile: ../workers/Dockerfile
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/manga_translator
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/app/storage
      - TEMP_DIR=/app/temp
    volumes:
      - ./data/storage:/app/storage
      - ./data/temp:/app/temp
    command: celery -A app.tasks worker --loglevel=info

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manga_translator
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 